### ISSUE TITLE
Stop Other Sounds when you Click a New one

### ISSUE THREAD

**Issue by brunocalado** [SvenWerlen/moulinette-sounds#4]
Hi

Can you make all other sounds stop when you click to play a new one?

**Comment by SvenWerlen** [comment]
Can you give me more information about this request?
Do you mean when you click on the sound board or directly in Foundry VTT (playlist)?

**Comment by brunocalado** [comment]
When I tell him to play another song, he starts playing the other one in conjunction with the one I asked.

Would it be possible to give an option to stop the current songs and play the selected one?

https://user-images.githubusercontent.com/4999783/127357781-ec1789f6-0891-49fd-8126-d22e2cd75a48.mp4

**Comment by SvenWerlen** [comment]
I won't implement this because it doesn't seem right. You might have a music playing in the background and want to play other sounds on top of it or even combine two (music + market place). You can easily stop playing a sound directly from moulinette sounds if you want to stop it. The new interface will also help you see if a sound is playing. 
![image](https://user-images.githubusercontent.com/938060/150889321-3fc14583-31f2-4246-bee4-5fb98bc62e0d.png)
